create table
    if not exists orb.prices (
        id text primary key,
        name text,
        model_type text,
        price_type text,
        cadence text,
        billing_mode text,
        currency text,
        external_price_id text,
        item_id text,
        billable_metric jsonb,
        billing_cycle_configuration jsonb,
        invoicing_cycle_configuration jsonb,
        conversion_rate double precision,
        conversion_rate_config jsonb,
        credit_allocation jsonb,
        discount jsonb,
        fixed_price_quantity double precision,
        invoice_grouping_key text,
        maximum jsonb,
        maximum_amount text,
        minimum jsonb,
        minimum_amount text,
        metadata jsonb,
        plan_phase_order integer,
        replaces_price_id text,
        dimensional_price_configuration jsonb,
        license_type jsonb,
        composite_price_filters jsonb,
        model_config jsonb,
        created_at timestamp not null,
        last_synced_at timestamptz
    );
