# Build step
FROM node:20-alpine
WORKDIR /app
COPY . .
RUN npm ci 
RUN npm run build

## Build step complete, copy to working image
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=0 /app/apps/node-fastify .
CMD ["npm", "start"]