import type { JsonSchema } from './types';

export const priceSchema: JsonSchema = {
  $id: 'priceSchema',
  type: 'object',
  properties: {
    id: { type: 'string' },
    name: { type: 'string' },
    model_type: { type: 'string' },
    price_type: { type: 'string' },
    cadence: { type: 'string' },
    billing_mode: { type: 'string' },
    currency: { type: 'string' },
    external_price_id: { type: 'string' },
    item_id: { type: 'string' },
    billable_metric: { type: 'object' },
    billing_cycle_configuration: { type: 'object' },
    invoicing_cycle_configuration: { type: 'object' },
    conversion_rate: { type: 'number' },
    conversion_rate_config: { type: 'object' },
    credit_allocation: { type: 'object' },
    discount: { type: 'object' },
    fixed_price_quantity: { type: 'number' },
    invoice_grouping_key: { type: 'string' },
    maximum: { type: 'object' },
    maximum_amount: { type: 'string' },
    minimum: { type: 'object' },
    minimum_amount: { type: 'string' },
    metadata: { type: 'object' },
    plan_phase_order: { type: 'number' },
    replaces_price_id: { type: 'string' },
    dimensional_price_configuration: { type: 'object' },
    license_type: { type: 'object' },
    composite_price_filters: { type: 'object' },
    model_config: { type: 'object' },
    created_at: { type: 'string' },
    last_synced_at: { type: 'string' },
  },
  required: ['id'],
} as const;
