name: CI

on:
  pull_request:
    branches: [master, develop]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Set up .env file
        run: |
          touch .env
          echo DATABASE_URL='postgres://postgres:postgres@127.0.0.1:55431/postgres?sslmode=disable&search_path=orb' >> .env
          echo ORB_API_KEY=sk_test_ >> .env
          echo ORB_WEBHOOK_SECRET=whsec_ >> .env
          echo SCHEMA=orb >> .env
          echo PORT=8080 >> .env
          echo API_KEY_SYNC=api_key_test >> .env

      - name: Install dependencies
        run: |
          npm ci

      - name: Prettier checks
        run: |
          npm run format:check

      - name: ESLint checks
        run: |
          npm run lint:check

      - name: Builds successfully
        run: |
          npm run build

      - name: Tests
        run: |
          docker-compose -f ./docker/compose.yml up -d
          npm run test
