name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Set up .env file
        run: |
          touch apps/node-fastify/.env
          echo DATABASE_URL='postgres://postgres:postgres@127.0.0.1:55431/postgres?sslmode=disable&search_path=orb' >> apps/node-fastify/.env
          echo ORB_API_KEY=sk_test_ >> apps/node-fastify/.env
          echo ORB_WEBHOOK_SECRET=whsec_ >> apps/node-fastify/.env
          echo SCHEMA=orb >> apps/node-fastify/.env
          echo PORT=8080 >> apps/node-fastify/.env
          echo API_KEY_SYNC=api_key_test >> apps/node-fastify/.env

      - name: Install dependencies
        run: |
          npm ci

      - name: Prettier checks
        run: |
          npm run format:check

      - name: ESLint checks
        run: |
          npm run lint:check

      - name: Builds successfully
        run: |
          npm run build

      - name: Tests
        run: |
          docker compose -f ./docker/compose.yml up -d --wait
          npm run test
